sudo: required
services:
  - docker

before_install:
  - docker build -t abz0/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run abz0/react-test npm test -- --coverage

after_success:
  - docker build -t abz0/multi-client ./client
  - docker build -t abz0/multi-nginx ./nginx
  - docker build -t abz0/multi-server ./server
  - docker build -t abz0/multi-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker Push abz0/multi-client
  - docker Push abz0/multi-nginx
  - docker Push abz0/multi-server
  - docker Push abz0/multi-worker
